### ISSUE TITLE
parun breaking in Hydra

### ISSUE THREAD

**Issue by adimako** [erdc/proteus#1013]
We get an index violation error when running for two phase flow. args_v is empty (is supposed to be empty as we only have options when running two phase 

Problems arise ins this line

https://github.com/erdc/proteus/blob/92e4b62fd8d9a38930f8315cd57ebd35e42f68ef/scripts/parun#L368

Suggested fix

add 

`args.append(opts.fileName)` before this line

We tested and it works, but it might not be conforming with the opts / args scope.

**Comment by tridelat** [comment]
@adimako what command do you use to launch the simulation? In 1.7, you should not use `-f` in front of the name of the file when using TwoPhaseFlow:
`parun [filename] --TwoPhaseFlow [...]`

**Comment by adimako** [comment]
Yes, I think we do not use the -f flag amymore. Suggest change in syntax rather than changing code. Ok to close?
parun **floating2D_2PF.py** --TwoPhaseFlow -f  -l 10 -v -O $HOME/PROTEUS/air-water-vv/inputTemplates/petsc.options.asm -D Trials/Python3Test/0.406497 -C "T=60 forced_freq_n=0.406497 genMesh=True use_gmsh=False"

**Comment by BranocRichards** [comment]
Yeah, this seems to solve the issue, sorry all.
