### ISSUE TITLE
Python3 data type errors in Parun

### ISSUE THREAD

**Issue by BranocRichards** [erdc/proteus#1016]
When running a case with the following:

system.setTimestepperType('Euler')
system.setCouplingScheme'CSS', prediction="backwardEuler")
The following error is obtained:
TypeError: expected bytes, str found

If the following (as i understand it, identical) options are tried:
system.setTimestepperType(b'Euler')
system.setTimestepperType('Euler'.encode('utf-8'))
I get this error:
AssertionError: b'Euler' not a valid choice.
(I've worked around this as Euler is the default, so the line is technically unnessecary in the current case)

However, when applying similar to the coupling scheme, there is no error.
system.setCouplingScheme(b'CSS', prediction="backwardEuler".encode('utf-8'))

There seems to be some inconsistency with types somewhere in parun that might extend further than these two options? This isn't causing me a problem right now, but figure it's worth bring to attention.

~~~EDIT~~~
Also found 
ProtChMoorings(beam_type=b"<string>")
m1.setName(b"<string>) 
to be nessecary

**Comment by adimako** [comment]
There was an error I had with gatherTimes, that it does not seem to be able to reproduce. I will let you know if it shows again

**Comment by cekees** [comment]
Closing; please reopen if it's still an issue.
