### ISSUE TITLE
Possible Rework of .h5-based Tests (because of PR #1039)

### ISSUE THREAD

**Issue by zhang-alvin** [erdc/proteus#1044]
Some issues are popping up in PR #1039, where tests are failing because comparisons are made against solution files computed from different meshes (due to version changes in the mesh generator). 

This leads to errors of the following type:
```    
def within_tol(x, y, atol, rtol):
        with errstate(invalid='ignore'):
>           return less_equal(abs(x-y), atol + rtol * abs(y))
E           ValueError: operands could not be broadcast together with shapes (599,) (711,)
```

One approach is to move towards metric-based tests. @manuel-quezada, you mentioned that some tests are already using a metric-based approach. Could you point me to some of those if you recall? 

I've looked into computing the L2 norms of scalars in the griffiths lane set of tests. It seems to be reasonable for the richards test, but I believe I'm seeing some compounding errors with the elastoplasticity test, where the test depends on the saved solution file for the richards problem. The result is that the L2 norms of each component in the displacement do not compare very well against the saved solution file (`elastoplastic_expected.h5`) when the mesh is changed. 

See https://github.com/erdc/proteus/blob/conda/proteus/tests/griffiths_lane_6/sm_gl_6_3d_p.py#L114

**Comment by zhang-alvin** [comment]
The following is the current approach to generating comparison files for tests. 

```
        expected_path = 'comparison_files/' + 'comparison_' + name + '_phi_t2.csv'
        #write comparison file
        #np.array(actual.root.phi_t2).tofile(os.path.join(self._scriptdir, expected_path),sep=",")
        np.testing.assert_almost_equal(np.fromfile(os.path.join(self._scriptdir, expected_path),sep=","),np.array(actual.root.phi_t2).flatten(),decimal=10)
```

The following are the remaining .h5 files in the tests directory, which represent the tests that still need to be modified:

```
/AddedMass/addedMass2D.h5
./SWEs/dam_over_bumps/comparison_files/SWEs_dam_over_bumps.h5
./SWEs/test_reflecting_BCs/comparison_files/SWEs_test_reflecting_BCs.h5
./SWEs/oneD_dambreak_flat_bottom/comparison_files/SWEs_oneD_dambreak_flat_bottom.h5
./SWEs/test_gauges/comparison_files/SWEs_test_gauges.h5
./SWEs/paraboloid_with_friction/oneD/comparison_files/SWEs_oneD_paraboloid_with_friction.h5
./SWEs/paraboloid_with_friction/twoD/comparison_files/SWEs_twoD_paraboloid_with_friction.h5
./TwoPhaseFlow/fillingTank.h5
./TwoPhaseFlow/risingBubble.h5
./cylinder2D/ibm_method/comparison_files/T4_rans3p.h5
./cylinder2D/ibm_method/comparison_files/T1_rans3p.h5
./cylinder2D/ibm_rans2p_3D/cylinder_ibm_T1_ibm_3D_rans2p.h5
./cylinder2D/conforming_rans2p/comparison_files/T1_rans2p.h5
./cylinder2D/sbm_3Dmesh/cylinder_sbm_mesh3D_T001_P1_sbm_3Dmesh.h5
./cylinder2D/sbm_method/comparison_files/T1_sbm_rans3p.h5
./cylinder2D/ibm_rans2p/comparison_files/T1_ibm_rans2p.h5
./cylinder2D/conforming_rans3p/comparison_files/T4P2.h5
./cylinder2D/conforming_rans3p/comparison_files/T8P2.h5
./cylinder2D/conforming_rans3p/comparison_files/T1P1.h5
./post_processing/comparison_files/test_bdm2_sshaped_region_expected.h5
./post_processing/comparison_files/test_bdm_sshaped_region_expected.h5
./post_processing/comparison_files/poisson_bdm1_test.h5
./post_processing/comparison_files/BDM_Test_File.h5
./LS_with_edgeBased_EV/MCorr/comparison_files/cons_ls_level_3_supg.h5
./LS_with_edgeBased_EV/MCorr/comparison_files/cons_ls_level_3_edge_based_EV.h5
./LS_with_edgeBased_EV/VOF/comparison_files/vof_level_3_EV2.h5
./LS_with_edgeBased_EV/VOF/comparison_files/vof_level_3_SUPG.h5
./LS_with_edgeBased_EV/VOF/comparison_files/vof_level_3_TaylorGalerkin.h5
./LS_with_edgeBased_EV/VOF/comparison_files/vof_level_3_EV1.h5
./LS_with_edgeBased_EV/VOF/comparison_files/vof_level_3_SmoothnessBased.h5
./LS_with_edgeBased_EV/VOF/comparison_files/vof_level_3_stab4.h5
./LS_with_edgeBased_EV/NCLS/comparison_files/ncls_level_3_pureAdvection_EV1.h5
./LS_with_edgeBased_EV/NCLS/comparison_files/ncls_level_3_non_saturated_ls.h5
./LS_with_edgeBased_EV/NCLS/comparison_files/ncls_level_3_saturated_ls.h5
./LS_with_edgeBased_EV/NCLS/comparison_files/ncls_level_3_pureAdvection_SUPG.h5
./griffiths_lane_6/elastoplastic.h5
./griffiths_lane_6/richards.h5
./SWFlow/comparison_files/solitary.h5
./SWFlow/comparison_files/parab1D.h5
./SWFlow/comparison_files/dam3Bumps.h5
./BDM2_Test_File_projection.h5
./BDM2_Test_File.h5
```

**Comment by manuel-quezada** [comment]
Hi @zhang-alvin . Sorry for the delay, I was on vacations and had almost no access to a good internet connection. Maybe you already found the tests. Anyway, the tests in `tests/elliptic_redist` consider the Linf norm of the solution. And in `tests/ProjScheme_with_EV' I consider a similar metric. Those are the only ones (that I did) and I could find, but I might be missing another one.

**Comment by zhang-alvin** [comment]
@manuel-quezada Okay, that's good to know since there seem to be some hard-coded values in those tests that you mentioned which i presume are the norms. Ultimately, we've opted to use .csv comparisons for simplicity/to avoid non-uniqueness.

**Comment by zhang-alvin** [comment]
I'm going to close this issue as this is resolved, with the exception of the pending merge of #1072.
