### ISSUE TITLE
Both conda and hashdist builds

### ISSUE THREAD

**Issue by JohanMabille** [erdc/proteus#1056]
A travis build based on hashdist should be added in #1039 so that both build approaches continue to be tested. This would ease the merge of the `conda` branch into `master.

**Comment by davidbrochart** [comment]
I have a PR for that: https://github.com/erdc/proteus/pull/1053

**Comment by zhang-alvin** [comment]
It looks like the failing test is very sensitive to the numerical packages being used and probably needs a proper overhaul more so than what I attempted. In that sense, I'd just turn off/skip the test for now.

**Comment by davidbrochart** [comment]
New PR is here: https://github.com/erdc/proteus/pull/1060

**Comment by zhang-alvin** [comment]
#1060 has been merged in. I think we can close this now.
