### ISSUE TITLE
Integrate xtensor into the hashdist build

### ISSUE THREAD

**Issue by JohanMabille** [erdc/proteus#1057]
Since the hashdist build needs to be maintained, if we want to migrate cython to xtensor, this latter should be integrated into the hashdist configuration.

**Comment by davidbrochart** [comment]
@cekees Is `hashdist` able to handle header-only libraries?
An alternative would be to have a mixed `conda`/`hashdist` environment, where `conda` would only install `xtensor-python` (which basically puts files in an include directory).

**Comment by davidbrochart** [comment]
I have a PR for that: https://github.com/erdc/proteus/pull/1054
It basically just downloads `xtensor-python` and its dependencies, and adds their include directories when compiling xtensor-based extensions.

**Comment by cekees** [comment]
Yes, I don't think there is already a base recipe for a header-only package, but you can so something like the autotools recipe without the `make` stage and simply copying the headers to the $ARTIFACT/include directory:

https://github.com/erdc/hashstack/blob/master/base/autotools_package.yaml

**Comment by JohanMabille** [comment]
`xtensor` is now integrated in the hdist build.
