### ISSUE TITLE
TPF: __init__ functions for models has unnecessary logic

### ISSUE THREAD

**Issue by zhang-alvin** [erdc/proteus#1067]
Based on discussions with @tridelat 

In the initialization of some models' coefficients class, like `RANS2P.Coefficients`, there is 
already logical evaluations based on the model attributes:

https://github.com/erdc/proteus/blob/master/proteus/mprans/RANS2P.py#L238-L275

This means that the class cannot be instantiated without appropriate attributes being set. This makes the code harder to read and is less user-friendly than necessary.

The proposal is to move such logical statements under a new function, e.g. `RANS2P.Coefficients.start()` after the user has specified the desired attributes. This has the added bonus of eliminating the need for the `CoefficientsOptions` class.

Such a change can be applied to all models.

**Comment by tridelat** [comment]
Closing as this was addressed with #1070
