### ISSUE TITLE
SWFlow and SWFlows

### ISSUE THREAD

**Issue by tridelat** [erdc/proteus#1108]
I just noticed that we have the 2 following subfolders in ./proteus: SWFlow and SWFlows.
They share a lot of common subfolders and files but are not exactly the same.
Is that intentional?

@cekees @ejtovar @zhang-alvin

**Comment by cekees** [comment]
No, I think it's just something that needs to be cleaned up when we refactor the SWFlow app

**Comment by ejtovar** [comment]
You can remove the directory ‘SWFLows’. The model files are not in that directory.
