### ISSUE TITLE
Clean up conversion to xtensor

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#1125]
- [ ] Convert to xtensor: https://github.com/erdc/proteus/blob/master/proteus/mprans/cRANS3PF.pyx
- [x]  Fix name: https://github.com/erdc/proteus/blob/master/proteus/mprans/RANS3PSed.cpp

@JohanMabille @davidbrochart @acatwithacomputer

**Comment by JohanMabille** [comment]
I will start to work on it tomorrow.

**Comment by tridelat** [comment]
@cekees cMoveMeshMonitor.pyx is not linking a .h file, it is a standalone cython file.
Do you mean this should be converted in C++ and pybind11/xtensor? (this would mean a complete rewriting of the logic inside)

**Comment by cekees** [comment]
@tridelat I see. No, I was thinking cMoveMeshMonitor.pyx was just a cython wrapper when I added that. I didn't realize it was actually written in Cython. I agree, that's not worthwhile, so I just removed that item.

**Comment by JohanMabille** [comment]
cRANS3PF was intentionally not converted to xtensor because it led to a compilation crash. This is probably due to the number of arguments of the methods, so we should be able to convert it when we have the dictionnary of numpy arrays (on which I started to work).

Investigating RANS3PSed issue for now.

**Comment by cekees** [comment]
Thanks @JohanMabille. You can see where I fixed a similar issue on the ADR classes here: https://github.com/erdc/proteus/pull/1097/files#diff-a4fd7c09419a8d7fc8a3552c9de3d404R21

On the RANS3PF, do you want to go ahead and push the pybind11 version with the compilation issue and let me take a look at it? We are seeing increased compilation requirements for the new pybind11 classes, both in terms of memory consumption of the compilation process and compile times. It may be that tweaking some compile options (e.g. switching to -O2 ) might help. Did you already try that?

**Comment by JohanMabille** [comment]
@cekees I've just pushed the fix, sorry for the delay.

Regarding RANS3PF, I reverted the change for the xtensor migration PR. I will add them again in a dedicated PR. I remembered we tried to switch to -O2 (and also Os at some point), but this flag was overriden, there was another -O3 flags added after and we didn't find where it came from.

**Comment by cekees** [comment]
Looks to me like they're being compiled with -O3: https://travis-ci.com/github/erdc/proteus/jobs/317490935

**Comment by cekees** [comment]
But, then I see we add -g -O2 at the end from the PROTEUS_OPT setting. I believe that should override the -O3. Anyway, If you add the dedicated PR with the RANS3PF change, I'll take a look.

**Comment by JohanMabille** [comment]
Ah, indeed. I was looking at my local build which is similar to the build with conda, where we removed switched from 03 to O2. 

I just opened #1128, for the migration of RANS3PF to xtensor
