### ISSUE TITLE
Hot start not advancing the time step

### ISSUE THREAD

**Issue by SavantG** [erdc/proteus#1235]
Hot starting using -H isn't progressing the time step on successful convergence. Below is a snippet of the log
"
[      39] ==============================================================
[      39] Solving over interval [ 4.30000e+01, 4.40000e+01]
[      39] ==============================================================
[      39] System time step t= 4.30067e+01, dt= 6.65406e-03
[      39] saving previous velocity dofs 0
[      39] Split operator iteration 0
[      39] Model: rans2p
[      39] Fractional step  4.30067e+01 for model rans2p
[      39] Model step t= 6.65406e-03, dt= 6.65406e-03 for model rans2p
[      39] Model substep t= 6.65406e-03 for model rans2p
[      39] Model substep t= 6.65406e-03 for model rans2p model.timeIntegration.t=  4.30067e+01
[      39] Maximum CFL = 0.75
[      39]    Newton it 0 norm(r) =  2.25572e+01                 norm(r)/(rtol*norm(r0)+atol) = 4.01017e+06 test=r
[      65] before ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= False ksp.its= 0 ksp.norm= 0.0
[      65] after ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= True ksp.its= 1 ksp.norm= 0.0 reason = 4
[      65] Maximum CFL = 0.7500612245648367
[      65]    Newton it 1 norm(r) =  3.62882e-01                 norm(r)/(rtol*norm(r0)+atol) = 64512.3 test=r
[      80] before ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= False ksp.its= 1 ksp.norm= 0.0
[      80] after ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= True ksp.its= 1 ksp.norm= 0.0 reason = 4
[      80] Maximum CFL = 0.7500737283082229
[      80]    Newton it 2 norm(r) =  2.87280e-02                 norm(r)/(rtol*norm(r0)+atol) = 5107.19 test=r
[      95] before ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= False ksp.its= 1 ksp.norm= 0.0
[      95] after ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= True ksp.its= 1 ksp.norm= 0.0 reason = 4
[      95] Maximum CFL = 0.7500718965588613
[      95]    Newton it 3 norm(r) =  4.40883e-03                 norm(r)/(rtol*norm(r0)+atol) = 783.792 test=r
[     110] before ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= False ksp.its= 1 ksp.norm= 0.0
[     110] after ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= True ksp.its= 1 ksp.norm= 0.0 reason = 4
[     110] Maximum CFL = 0.7500720966303199
[     110]    Newton it 4 norm(r) =  7.68020e-04                 norm(r)/(rtol*norm(r0)+atol) = 136.537 test=r
[     125] before ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= False ksp.its= 1 ksp.norm= 0.0
[     125] after ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= True ksp.its= 1 ksp.norm= 0.0 reason = 4
[     125] Maximum CFL = 0.7500720785814149
[     125]    Newton it 5 norm(r) =  1.40566e-04                 norm(r)/(rtol*norm(r0)+atol) = 24.9895 test=r
[     139] before ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= False ksp.its= 1 ksp.norm= 0.0
[     140] after ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= True ksp.its= 1 ksp.norm= 0.0 reason = 4
[     140] Maximum CFL = 0.7500720798034661
[     140]    Newton it 6 norm(r) =  2.57249e-05                 norm(r)/(rtol*norm(r0)+atol) = 4.57331 test=r
[     154] before ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= False ksp.its= 1 ksp.norm= 0.0
[     154] after ksp.rtol= 0.01 ksp.atol= 5.625e-08 ksp.converged= True ksp.its= 1 ksp.norm= 0.0 reason = 4
[     154] Maximum CFL = 0.750072079766989
[     154]    Newton it 7 norm(r) =  4.93684e-06                 norm(r)/(rtol*norm(r0)+atol) =  8.77660e-01
[     154] Max local conservation (dgp1 enriched all elements) =  9.61164e-09
[     154] Global divergence =  1.66533e-15
[     154] Step Taken, t_stepSequence= 43.00665405696237 Model step t= 6.65406e-03, dt= 6.65406e-03 for model rans2p
[     154] Model step t= 6.65406e-03, dt= 6.65406e-03 for model rans2p
[     154] Model substep t= 6.65406e-03 for model rans2p
[     154] Model substep t= 6.65406e-03 for model rans2p model.timeIntegration.t=  4.30067e+01
"

**Comment by zhang-alvin** [comment]
Closing this as #1236 should have addressed this.
