### ISSUE TITLE
How to compute the SolitaryWave in WaveTools

### ISSUE THREAD

**Issue by whtsao** [erdc/proteus#1267]
@adimako Hi, I have a simple question regarding the ‘SolitaryWave’ in WaveTools. I studied the first-order Boussinesq’s solitary wave solution in “Boussinesq, M.J., 1871.Théorie de l’intumescence liquide, appellee onde solitaire ou de translation, se propageant dans un canal rectangulaire. C. R. l'Acad. Sci.72, 755–759.”, but found our equation is slightly different from Eq. (42) shown in Boussinesq’s paper. The difference is shown in the red circle.
![image](https://user-images.githubusercontent.com/87154971/189544300-198be1b7-8fe5-4204-90b7-d60bd1679892.png)
The second question is that I can’t relate these equations with what was actually built in Proteus to compute the velocity. I guess maybe it is an approximation by series expansion. I need some help from the author of the code.
![image](https://user-images.githubusercontent.com/87154971/189544321-382b4806-8043-450d-8f44-aa3b0f3a38b3.png)
However, in my current test, the velocity field (u,v) looks reasonable to me (the solitary wave travel to the right). For the vertical component, the right side of the crest is positive (wave goes up) while the left side of the crest is negative (wave goes down). Therefore, I would like to clarify these equations so that I can give another solitary wave code by Fenton's solution. Thank you!
![image](https://user-images.githubusercontent.com/87154971/189544333-a1ea62c4-bfd8-4539-855f-7663c8f84b2e.png)

**Comment by adimako** [comment]
@whtsao sorry for the late reply. The equations were copied essentially from the waves2foam library and in particular from https://github.com/ogoe/waves2Foam/blob/master/src/waves2Foam/waveTheories/solitary/solitaryFirst/solitaryFirst.C - see function eta and U. The reason for that is that I had validated whilst at HR Wallingford with analytical solutions. The original reference is         Hydrodynamics of Coastal Regions
        Ib A. Svendsen and Ivar G. Jonsson
        1982
        Den private ingenioerfond
        Technical University of Denmark

**Comment by whtsao** [comment]
@adimako thanks for the information. I will go thriugh the wave theory and the solutions.
