### ISSUE TITLE
CNW with CombineWaves, RandomWaves, NewWave

### ISSUE THREAD

**Issue by ghylander** [erdc/proteus#1268]
Hi, I'm looking to create a CNW (Time Domain Simulation of Jack-up Dynamics With the Extremes of a Gaussian Process, Taylor et al 1997) eta time series

I'm trying to generate it using the `wavetools` module, but I'm unsure about certain steps to create the involved classes.

First, I'm trying to create the `NewWave` object.
I had previously implmented this myself, approaching the problem by assuming very large water depth, unidirectional waves, etc
After reading through the `NewWave` class help and looking at the source code, I'm having a bit of trouble generating the `NewWave `object using these simplifications
How would I approach this?
I assume that I can pass a 1-element array to both the `waveDir` and `g` arguments to only consider a single wave direction, but is there any way of considering water depth large (so tanh(kd) ≈ 1)?  Does inputting a sufficiently large depth parameter (i.e., ~500m) work?

Additionally, I'm unsure what the `mwl` argument is used for, or how is it defined. I assume it's a parameter used to calculate the velocity of wave particles, but I'm not interested in that output. Is it possible to not input such argument (or inputting a "garbage" without it affecting the eta time series)?

These doubts apply to the `RandomWaves` class too (`mwl`, `depth`, `waveDir` and `g`)

Finally, regarding the generation of a CNW, would the `CombineWave` class be a suitable match?
The docs and source code provide little insight on the inner workings of the class

**Comment by adimako** [comment]
hello @ghylander. Few points to help you:

- mwl is the level of the water according to coordinates, e.g. if your gravity direction is aligned with the z axis and the water level is set at z=10 - then mwl = 10
- depth is the distance from the seabed (assuming a flat seabed) e.g if the seabed is at z=-10 then according to previous example, depth=20
- waveDir is the unit vector aligned with direction of the wave according to the global coordinate system, e.g if your waves run along the x axis then waveDir = [1,0.,0.]
- g is the gravity acceleration vector e.g. for the previous example g=[0,0,-9.81]. This means that the gravity is aligned with the z axis and pointing downwards (toward negative values)
- For deep water waves assume that the depth is >0.5 x wavelenght. The wavelength in deep water is depth = 1.56 T^2 where T is the period

**Comment by ghylander** [comment]
Hi @adimako, thanks for your comment.

The first two points (regarding `mwl` and `depth`) were very insightful. I didn't understand the difference between the two. Now I understand the former is the distance between the z=0 origin point and the letter the actual distance between the surface and the seabed.

Thanks for the comments on how to input the `waveDir` and `g` parameters, I had the wrong idea about how to input them.

Thanks for your comments! I was able to succesfully create the objects and execute the `eta` and `writeEtaSeries` methods.


My question regarding the suitability of the `CombineWaves` class to create a Constrained NewWave eta tiemseries from the `NewWave` and `RandomWaves` objects does remain.

I also have found that the wavetools.NewWave.writeEtaSeries() method does not write the results to file (as it seems it should do:

![image](https://user-images.githubusercontent.com/74593034/194819809-5986aac1-dc28-4516-8e7c-b3655781dd85.png)

Is there any extra step to be taken? Not that it's an issue, Ican simply write to file the returned ndarray, but it seems this may be a bug or outdated docs?

**Comment by cekees** [comment]
The `CombineWaves` class assumes the principle of superposition applies to solutions. That is, it sums wave heights (or velocities) over the list of wave objects ("wave conditions") provided by the user: https://github.com/erdc/proteus/blob/main/proteus/WaveTools.py#L3328.

**Comment by ghylander** [comment]
I see thanks

Would you be interested in a CNW theory implementation for proteus?
I can provide the basic python code, but I don't have experience with cython to the point where I could fully implement it

**Comment by cekees** [comment]
Yes, probably the thing to do is get things implemented in WaveTools.py first, along with tests covering the new class added to https://github.com/erdc/proteus/blob/main/proteus/tests/wave_tests/test_wavetools.py.  The process is basically to fork proteus and then do a pull request from your fork with your changes. The general requirements for accepting a PR are that it provides something useful and does not decrease test coverage. We can worry about optimizing it via Cython or pybind once the pure Python PR is ready to merge. @adimako may have more comments on what constitutes useful functionality for the WaveTools module--he is the main author of that. If you wanted to continue with the PR, you can close this issue. We can discuss further once you have an initial PR.

**Comment by ghylander** [comment]
Some notes before I get to work and opening a PR

How would you like the class to be used?
To apply the theory, first one would create a random wave, with its own Hs, Tp, etc
Then, the NewWave is generated (using the appropriate Hs, Tp, etc). The NewWave formula is not applied, however. Only the auto-correlation function (or unit NewWave) is needed. 
The required parameters for the CNW are the following:

![image](https://user-images.githubusercontent.com/74593034/195786946-5a252a31-8453-48b2-8755-4920bc2ad165.png)
(image source: Non-Linear Analysis of Jack-Up Structures Subjected to Random Waves, M. Cassidy 1999)

 (1) The random waves surface elevation time series η<sub>rw</sub>(t)
 (2) The unit NewWave r(t)
 (3) The NewWave scaling factor (α, A<sub>cr</sub> or `wt.NewWave()` 'Hs' parameter)
 (4) The random waves surface elevation at t=t<sub>f</sub> or `wt.NewWave()` 'tfocus' parameter)
 (5) The unit NewWave slope ṙ(t)
 (5*) λ<sup>2</sup>, extracted from the 2<sup>nd</sup> spectral moment of the wave energy spectrum (m<sub>2</sub>=λ<sup>2</sup>·σ<sup>2</sup>)
 (6) The constrained surface slope ἁ (for a crest, ἁ=0)
 (7) The random waves surface elevation at t=t<sub>f</sub>

Given all of this, how would you like the class to be constructed?
Do you want to generate a RandomWaves object and pass it to the ConstrainedNewWave class?
Do you want the random waves to be generated fully inside the ConstrainedNewWave class?
How do you want to define at what point in time inside the random waves eta series the NewWave is constrained? (In the equation above, t=0 is defined as t<sub>f</sub>)

Any option is good for me, but how do you want the object to be constructed by the user?
