### ISSUE TITLE
Reference of TimeSeries in WaveTools

### ISSUE THREAD

**Issue by whtsao** [erdc/proteus#1271]
I am using 'TimeSeries' command in 'WaveTools.py'.
For writing paper purpose, could you please provide the reference of this function?
A paper, keyword, or the name of the method would help.
Thank you.

**Comment by cekees** [comment]
I think this would be good: https://doi.org/10.1680/jencm.17.00016 @adimako may have other ideas. You can also site the latest proteus release with the zenodo DOI: 

https://doi.org/10.5281/zenodo.6787657

**Comment by adimako** [comment]
Yes this is the correct reference of timeseries

**Comment by whtsao** [comment]
Thank you!
