### ISSUE TITLE
Reduce window effect of 'TimeSeries'

### ISSUE THREAD

**Issue by whtsao** [erdc/proteus#1272]
I would like to know how to reduce the window effect when operating ‘TimeSeries’ function for constructing irregular waves.
In my current test, I can only reconstruct an accurate time history by using a small period of data truncated from the original measurement, e.g., use 100s window out of a 1000s data as the time series input.
Could I use the entire period of the original data as input without distortion by applying ‘window_params’ in the ‘TimeSeries’?
@adimako Do you have any comment? Thank you.

**Comment by adimako** [comment]
I don't have the code right in front of me right now but you should be able to switch to direct reconstruction or use only one or two windows.

But be aware that you need drastically increase the number of reconstruction frequencies so than you have enough available to cover the length of the time series. If your window duration is 100s and your overall series is a 1000s I think you should use at least 10x as much frequencies to maintain the same resolution
