### ISSUE TITLE
Makefile does not detect when a library dependency in hashstack is out of date

### ISSUE THREAD

**Issue by ahmadia** [erdc/proteus#147]
Should force a clean rebuild since Python `setup.py` is not smart enough to detect this situation.

**Comment by cekees** [comment]
We only build the profile if it doesn't exist (i.e. PROTEUS_PREFIX/artifact.json is missing). After that we intentionally don't force rebuilds and push off additional management of the stack to the user (i.e. do a `make distclean` and git submodule or modifications in in ./stack to trigger rebuilds.
