### ISSUE TITLE
model.levelModelList[-1].timeIntegration.t is not properly set when attachModel is called

### ISSUE THREAD

**Issue by ahmadia** [erdc/proteus#198]
The time is set to 1e6.  The current workaround with the Gauges is to assume this value is actually t=0, but this is dangerous as well.

**Comment by ahmadia** [comment]
Looks like it is currently set to 1e6 on the first call to calculate as well.

**Comment by cekees** [comment]
believe this was fixed... @adimako please reopen if you've been dealing with time history issues with the Gauges.
