### ISSUE TITLE
Error from Proteus Generated Poly FIle

### ISSUE THREAD

**Issue by tweigand** [erdc/proteus#200]
I am using triangle for mesh generation. I am refining the domain in proteus and proteus is generating a new polyfile. When I try to re-run the simulation, proteus is getting stuck on reading the polyfile. I found that at the bottom of the file if I change #no regions specified to a zero, proteus runs. The error is found here:

  File "/Users/tim/Programming/proteus/darwin/lib/python2.7/site-packages/proteus/Domain.py", line 235, in **init**
    self.readPoly(fileprefix)
  File "/Users/tim/Programming/proteus/darwin/lib/python2.7/site-packages/proteus/Domain.py", line 341, in readPoly
    regionLine = f.readline().split()

It seems like the code should be working if I look at line 340 of Domain.py
while len(regionLine) == 0 or regionLine[0][0] == '#':

**Comment by tweigand** [comment]
I can use the Triangle command line P to supress the output of the poly file and that works.

**Comment by tweigand** [comment]
Also, the polyfile I originally generated runs fine with Triangle.

**Comment by adimako** [comment]
@cekees not sure about that

**Comment by cekees** [comment]
closing; reopen if this is still an issue. There are several workflows for meshing using existing polyfiles, the simplest being setting `genMesh=False` and set the name of the polyfile on the domain object. It doesn't need to parse the polyfile.
