### ISSUE TITLE
Scalable gauges

### ISSUE THREAD

**Issue by ahmadia** [erdc/proteus#205]
The current gauge design philosophy assumes that all gauges will be known to all processes.  This will not scale well beyond 10s of thousands of processes.  In order to fix these, the gauge specification code should provide a functional approach to gauge design.  That is, the user might specify that they want a horizontal line at grid resolution across the space along a given plane.  This information would then be used to programmatically create local gauges.

Also, the gauges need to support a non-CSV format for true scalability.

**Comment by adimako** [comment]
@cekees looks addressed, closing
