### ISSUE TITLE
Add Entropy Viscosity implementation for scalar problems

### ISSUE THREAD

**Issue by mfarthin** [erdc/proteus#330]
Implement the Entropy Viscosity method from Guermond, Popov et al in proteus
- [ ] low-order viscosity
- [ ] high-order viscosity using the entropy residual
- [ ] Flux Corrected Transport limiting

**Comment by mfarthin** [comment]
@tweigand @cekees 
I added a notebook showing the Entropy Viscosity approximation I went over in the workshop. It's under `proteus/tests/EV/notes` on the `add_ev` branch. 

@tweigand you will need to make sure you don't use this branch for debugging the membrane problem since it has code from the `add_first_order_maxmin` branch that will affect the standard approximation unless you turn it off in the `OneLevelTransport` class.

It required an upgrade of `cython` to 0.23. You can do this by switching the `stack/pkgs/cython.yaml` file to have
```
  - url: http://cython.org/release/Cython-0.23.4.tar.gz
    key: tar.gz:73cc73hogxlmyauip4po6tsjklexiaxn
```

**Comment by adimako** [comment]
@cekees @manuel-quezada this should be closed no?
