### ISSUE TITLE
SpatialTools and BoundaryConditions changes

### ISSUE THREAD

**Issue by tridelat** [erdc/proteus#351]
After merging refactor_Domain into master (https://github.com/erdc-cm/proteus/pull/292), there are still some additions/changes that could be made:
- [ ] **proteus/SpatialTools.py** and **proteus/mprans/SpatialTools.py**
  - [x] integrate Chrono::Engine (or other) for rigid body calculations and collision detection
  - [x] test ShapeSTL class further
  - [x] use consistent notation for BC of predefined shapes' segments/facets (left/right front/back etc..)
  - [x] add the possibility to attach mesh refinement/coarsening to specific shapes/regions
  - [x] improve docstrings
  - [ ] develop more tests in test_spatialtools.py
- [ ] **proteus/BoundaryConditions.py** and **proteus/mprans/BoundaryConditions.py**
  - [x] remove dependencies to Context variables for some BC
  - [ ] test all BCs defined in mprans module
  - [x] improve docstrings
  - [ ] develop more tests in test_boundaryconditions.py

**Comment by adimako** [comment]
@tridelat do we need to do anything more about this? I know that there are some untested BC's perhaps it is the time to comment these out for now and put them back (with tests) if we want to use them?

**Comment by tridelat** [comment]
@adimako I would say that we can close this as all the BCs we actually use are tested.
