### ISSUE TITLE
MPRANS Tests

### ISSUE THREAD

**Issue by alistairbntl** [erdc/proteus#408]
PR #402 introduced an error in mprans which was not caught by the default Travis tests.  I submitted a fix in #407 but it seems a test should be added to prevent future regression.

I'm wondering if there are some tests floating around that support MPRANS and whether we could include a few of these in the default Travis tests.

Thoughts @cekees, @adimako, @tridelat?

**Comment by adimako** [comment]
We have much more tests now including standard proteus ones that check mprans, as well as ones referring to air-water-vv (and we will hopefully keep adding). Closing this as not relevant anymore
