### ISSUE TITLE
ADR Entropy Viscoisty

### ISSUE THREAD

**Issue by tweigand** [erdc/proteus#458]
- [ ] Write out Entropy Viscosity Algorithm from VOF.h
- [ ] Get ADR running for sample problem
- [ ] Incorporate Entropy Viscosity Algorithm from VOF into ADR with no diffusion and reaction
- [ ] Add diffusion implicitly with forward and backward Euler

**Comment by adimako** [comment]
@manuel-quezada @cekees this should be over now?
