### ISSUE TITLE
Installing error on stampede

### ISSUE THREAD

**Issue by yuxianglin** [erdc/proteus#459]
Hi,

I am installing Proteus on Stampede machine, but when I export PROTEUS_ARCH='stampede.gnu' and make, it prompt error when building openjpeg saying CMake Error: The source directory "/home1/04328/shawnlin/.hashdist/tmp/openjpeg-veyziolxw7sc" does not appear to contain CMakeLists.txt.

However this error never show up in my personal machine. I have attached screenshot below. Anyone has advice regarding to this?

![screenshot from 2016-10-28 21-59-50](https://cloud.githubusercontent.com/assets/17280119/19826790/e741fa98-9d59-11e6-88be-99692cd8283a.png)

Yuxiang

**Comment by cekees** [comment]
In `/proteus/stack/default.yaml`, what does your entry for openjpeg look like? Here is what it  looks  like for the default  Linux branch: https://github.com/hashdist/hashstack/blob/stable/proteus/examples/proteus.linux2.yaml#L20

Namely, it explicitly uses the 2.1 version of openjpeg. It may be that the proteus.stampede.gnu profile needs a little bit  of updating.

**Comment by yuxianglin** [comment]
It looks something like this. It seems there is not openjpeg specification here however

![screenshot from 2016-11-01 11-14-33](https://cloud.githubusercontent.com/assets/17280119/19897018/65f1b780-a024-11e6-94c4-222365c804bb.png)

**Comment by cekees** [comment]
OK, go ahead and put one in as in the stable/proteus branch.

**Comment by yuxianglin** [comment]
Thank you for advice Cris, it did works. However, another installation issue prompt out, says

![screenshot from 2016-11-01 18-43-22](https://cloud.githubusercontent.com/assets/17280119/19911700/2e8d32f8-a063-11e6-9b55-66dbb96acb31.png)

Any advise would be appreciated.

**Comment by cekees** [comment]
Hi @yuxianglin , this fell off my radar. Did you git past this our give up/move on?

**Comment by adimako** [comment]
Closing this as this is two years now. Can be raised as a new issue
