### ISSUE TITLE
AnalyticalSolutions module

### ISSUE THREAD

**Issue by alistairbntl** [erdc/proteus#468]
@cekees 

In the AnalyticalSolutions module starting at line 884, there are several thousand lines of commented out code.  There is little documentation supporting this code, so I'm wondering if it might be cleaner to remove it.  If it is code that is needed in the future, it will be available through the version control.

Perhaps this relates to a broader question of what to do with old code that is not being still has value.

**Comment by adimako** [comment]
@cekees @alistairbntl has the recent upgrade we did affected this issue? I see that Analytical solution is around. I tried removing at some point the cAnalyticalSolution file, but this is still required by the code

**Comment by cekees** [comment]
fixed
