### ISSUE TITLE
Partition mesh fails

### ISSUE THREAD

**Issue by yuxianglin** [erdc/proteus#541]
Hi:

I am running a large mesh problem with 40 million elements(approximately 6,400,000 nodes) with 4096 cores with these files https://github.com/yuxianglin/air-water-vv/tree/yuxianglin/3d/Solitary_wave_obst_sym, the mesh is successfully generated, however, the partition always fail with assertion error shown below, 
![screenshot from 2017-06-13 14-24-54](https://user-images.githubusercontent.com/17280119/27204236-96602fc8-51ef-11e7-9ed8-a9c0ce91c54b.png)

When I coarse the mesh with fewer cores, it however can run without any problem.

Any advise would be appreciated.

**Comment by yuxianglin** [comment]
PS:
The command I ran on stampede is ibrun -np 4096 parun tank_so.py -l 3 -v -F -m
and the tetgen command is tetgen -KVApq1.35q12feena7.1458333333333354e-06 mesh.poly

**Comment by zhang-alvin** [comment]
I can't say that I have a solution but possibly a work-around. There's a choice in how you want to partition your mesh. Usually you specify this in your case-setup file (`tank.py`?):

```
parallelPartitioningType = proteus.MeshTools.MeshParallelPartitioningTypes.element
#parallelPartitioningType = proteus.MeshTools.MeshParallelPartitioningTypes.node
nLayersOfOverlapForParallel = 0
```

The error message that you have seems to indicate that the mesh is being partitioned by nodes, so you might want to try partitioning by elements to potentially get further.

**Comment by yuxianglin** [comment]
@zhang-alvin Thanks for your suggestion, I'll try this in another running

**Comment by yuxianglin** [comment]
@zhang-alvin 
In https://github.com/erdc-cm/proteus/blob/master/proteus/MeshTools.py#L3712 it assert the parallelpartition type to be node if you want partition from files, ie, and -F for large meshm however.

**Comment by yuxianglin** [comment]
@zhang-alvin @cekees partition mesh from element is not defined if we add -F to our command
https://github.com/erdc-cm/proteus/blob/master/proteus/MeshTools.py#L674

**Comment by cekees** [comment]
Yes, you can only use -F with a zero overlap node- based partition. Usually I pregenerate the mesh on the commend line and set genMesh to False when using -F.

**Comment by cekees** [comment]
When I run on I see ```
% tetgen -VApq1.35q12feena7.1458333333333354e-06 mesh.poly
Opening mesh.poly.
Constructing Delaunay tetrahedralization.
  Sorting vertices by a bsp-tree.
  Number of tree nodes: 2.
  Maximum tree node size: 41.
  Maximum tree depth: 0.
  Incrementally inserting vertices.
Delaunay seconds:  0
Creating surface mesh.
  Unifying segments.
  Merging coplanar facets.
  Marking acute vertices.
Recovering boundaries.
  Delaunizing segments.
  0 protecting points.
  Constraining facets.
  84 subedge flips.
  1 cavities remeshed.
Boundary recovery seconds:  0.01
Removing exterior tetrahedra.
Warning:  Detecting an open face (78, 47, 17).```

I'm concerned about the open face. My suspicion is that the partitioning is failing because the mesh is not really valid.

**Comment by yuxianglin** [comment]
@cekees OK, I made a mistake in constructing the mesh, because the mesh is successfully generate so I omit that warning. I have modified that part, hopefully this time will run

**Comment by cekees** [comment]
If you push your inputs on your air-water-vv fork I'll try it again.

**Comment by yuxianglin** [comment]
https://github.com/yuxianglin/air-water-vv/tree/yuxianglin/3d/Solitary_wave_obst_sym @cekees

**Comment by cekees** [comment]
Sorry, I've been traveling nonstop. Where does this issue stand?

**Comment by zhang-alvin** [comment]
Having seen the same issue with the marin case that's generated with a tetgen mesh, @cekees suggested to add the `ee` flag to the tetgen input which yields a full-edge file as opposed to an edge file comprising subsegments. For example, if the initial set of options were: 
`triangleOptions="VApq1.25q12ena%e" % ((he**3)/6.0,) `
we now have,
`triangleOptions="VApq1.25q12eena%e" % ((he**3)/6.0,)`

This resolves the assertion errors when reading the mesh in parallel with the `-F` option in `parun`.

**Comment by zhang-alvin** [comment]
I'm quite sure the options mentioned in #641 will resolve the issue, so I'll close this for now.
