### ISSUE TITLE
Added mass effect - Robin-Neumann boundary conditions

### ISSUE THREAD

**Issue by tridelat** [erdc/proteus#560]
A way to set Robin-Neumann boundary conditions in Proteus should be implemented for limiting the added mass effect due to FSI partitioned algorithm.

**Comment by alistairbntl** [comment]
@tridelat - I'm actually looking at trying to do something similar in some in our discrete operators for the pressure convection diffusion problems so let's make sure to stay in communication about our progress on this.

**Comment by cekees** [comment]
I discussed this with Banks at USNCCM. I think I know how to do this now.  It's not really even a standard Robin condition. It ends up coupling all the pressure DOF on the solid boundary, and they do it by adding an additional equation.

**Comment by tridelat** [comment]
@cekees is there literature about how they implemented it?

**Comment by cekees** [comment]
He didn't reference any literature on actual implementation details. You might be able to look in Overture. What he said was that they ADD an additional equation that sets basically uses the calculated body acceleration (from integrating the force around the boundary) to the fluid surface accelerations. That's why it couples ALL the pressure nodes on the boundary to ALL the velocity nodes on the boundary.

**Comment by cekees** [comment]
http://www.overtureframework.org/

**Comment by tridelat** [comment]
@cekees does this differ from http://www.sciencedirect.com/science/article/pii/S0021999117300256 ?
In this paper from Banks (2017), the fluid pressure and body acceleration are set together, and then the body velocity is updated with the calculated acceleration. I am wondering if this would work from more complex multi-body systems such as ones with mooring cables for example, as we cannot really set a fixed acceleration of the body in this case (esp. if we use substeps for multi-body calculations).

**Comment by tridelat** [comment]
Closing because #658 resolved the added mass effect issue (but without the need of Robin-Neumann boundary conditions)
