### ISSUE TITLE
c asserts not being triggered

### ISSUE THREAD

**Issue by alistairbntl** [erdc/proteus#574]
I imagine this could be the way I've compiled Proteus, but on several occasions I've noticed that asserts inside the c-code which should have been triggered were not.
In particular I just noticed that the assert in `superluWrappersModule.c` on line 122 was not triggered in a simulation I'm working on.
I realize this issue is a bit vague but I wanted to post it for future reference.

**Comment by cekees** [comment]
The macro NDEBUG usually determines whether asserts are enforced.
