### ISSUE TITLE
use precise chrono compile flags for chrono extensions

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#576]
I fixed the chrono extension builds with travis by explicitly adding '-mavx', but  we can do better than that.

We pull in information about hashdist packages from their build artifact using this script:
https://github.com/erdc-cm/proteus/blob/master/proteus/config/default.py#L38

We can extend this to pull in the chrono compilation options roughly as follows. 

1) get the installed ChronoConfig.cmake file:
```
CHRONO_INCLUDE_DIR, CHRONO_LIB_DIR = get_flags('chrono')
chrono_cmake_config_file = open(os.path.joint('CHRONO_LIB_DIR','cmake','ChronoConfig.cmake'),'r')
```
2) Parse that file to extract the string from the CHRONO_CXX_FLAGS line that looks something like this:

set(CHRONO_CXX_FLAGS " -std=c++14 -pthread -fopenmp  -march=native -msse4.2 -mfpmath=sse  -march=native -mavx2  -march=native -mfma")

3) Add those CHRONO_CXX_FLAGS to the mbd extensions in setup.py.

In an effort to be more systematic about our issues I'm assigning primary responsibility to @tridelat but Milad and I will help get this done before Milad leaves. @alistairbntl and @zhang-alvin it would be good to look at how similar things are done for petsc and scorec respectively.

**Comment by tridelat** [comment]
Closing because #658 resolved this issue (commit b5e9581)
