### ISSUE TITLE
WallFunctions module failure for high refinement

### ISSUE THREAD

**Issue by Giovanni-Cozzuto-1989** [erdc/proteus#590]
Wall functions improvement within the BoundaryConditions module.

This is an issue within this pull request: https://github.com/erdc-cm/proteus/pull/584. 
The test problem is in this repository: https://github.com/erdc-cm/air-water-vv/tree/6afbf6eee9ed738e7a05b341a3f4ba2c346a8be6/2d/turbulentChannel.

In case of using an high refinement at the near-wall region the module fails in extracting the right velocity from the model.
"nan" value is returned as velocity at the first computational node after the boundary.

With a coaser mesh refinement this doesn't happen.

![immagine](https://user-images.githubusercontent.com/15638848/29132077-e12603ea-7d26-11e7-8ed5-12040831b737.png)

@cekees @tridelat @adimako

**Comment by adimako** [comment]
@tridelat, not sure about this. We need to re-run the flat wall benchmarks. @Giovanni-Cozzuto-1989 if you are still around, did you do anything to solve it?
