### ISSUE TITLE
Review parallelism and flcbdfwrappers.so

### ISSUE THREAD

**Issue by ahmadia** [erdc/proteus#61]
flcbdfwrappers.so requires that MPI has been initialized before it is called.  Unfortunately, this can lead to erroneous results when functions are called before MPI has been initialized.  We need to perform the following tasks:
- [ ] - Ensure that if MPI returns an error, this error is propagated up to an error handler.
- [ ] - When flcbdfwrappers is initializated, it will ensure that MPI is called and that a default communicator is set.

**Comment by cekees** [comment]
Mostly addressed when we shifted control to mpi4py and refactored partitioning and flcbdfWrappers with Cython.
