### ISSUE TITLE
Exception TypeError: "'float' does not have the buffer interface" in 'mprans.BoundaryConditions.

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#672]
Anybody seen this error?

> Exception TypeError: "'float' does not have the buffer interface" in 'mprans.BoundaryConditions.__cppClass_WavesCharacteristics.__cpp_calculate_pressure' ignored

cc @adimako

**Comment by tridelat** [comment]
@cekees I think this might be an array that has not been initialised, and it most likely is `self._b_or` ( https://github.com/erdc/proteus/blob/master/proteus/mprans/BoundaryConditions.py#L959 ). This is the boundary orientation array, usually something like `np.array([1.,0.,0.])`

**Comment by cekees** [comment]
Do you see anything missing here: ```
# DOMAIN
domain = Domain.PiecewiseLinearComplexDomain()

# TANK
tank_dim = [opts.tank_x, opts.tank_y, opts.tank_z]
tank = st.Tank3D(domain, dim=tank_dim,)
sponges = {'x-': opts.tank_sponge_xn,
           'x+': opts.tank_sponge_xp,
           'y-': opts.tank_sponge_yn,
           'y+': opts.tank_sponge_yp}
if opts.tank_sponge_lambda_scale and opts.waves:
    for key in sponges:
        sponges[key] *= wave.wavelength
tank.setSponge(x_n=sponges['x-'], x_p=sponges['x+'], y_n=sponges['y-'], y_p=sponges['y+'])
# boundary conditions
tank.BC['z+'].setAtmosphere()
tank.BC['z-'].setNoSlip()
tank.BC['x-'].setUnsteadyTwoPhaseVelocityInlet(wave=wave,
                                               smoothing=3.0*opts.he,
                                               vert_axis=2,
                                               wind_speed=np.array([0.,0.,0.]))
tank.BC['x+'].setHydrostaticPressureOutletWithDepth(seaLevel=opts.water_level,
                                                    rhoUp=rho_1,
                                                    rhoDown=rho_0,
                                                    g=g,
                                                    refLevel=opts.tank_z,
                                                    smoothing=3.0*opts.he,
                                                    U=np.array([opts.speed,0.,0.]),
                                                    Uwind=np.array([0.,0.,0.]),
                                                    vert_axis=2)
tank.BC['y-'].setNoSlip()
tank.BC['y+'].setNoSlip()
tank.BC['sponge'].setNonMaterial()
```
I think this came up when I added the outflow hydrostatic condition.

**Comment by cekees** [comment]
The problem is generate by the wave object. If I switch it to Monochromatic from SteadyCurrent then the issue goes away.

**Comment by cekees** [comment]
I was just passing in a scalar for the current, needs to be a numpy array:

`    wave = wt.SteadyCurrent(U=np.array([opts.speed,0.,0.]),
                            mwl=mwl,
                            rampTime=opts.ramp)
`

**Comment by tridelat** [comment]
I see, problem solved? We could put assertions in the functions to avoid this kind of errors

**Comment by adimako** [comment]
@cekees steady current should indeed use a numpy array in vector form. I copy-paste an error message because I believe I am doing this check somewhere else in WaveTools

**Comment by adimako** [comment]
This is sorted at https://github.com/erdc/proteus/pull/678. If a scalar is given by accident, an error message will pop up from Wave Tools. I will close this one
