### ISSUE TITLE
Meshtools.genMeshWithTetgen() reads only nodes and elements, no faces

### ISSUE THREAD

**Issue by xiaowang1999** [erdc/proteus#681]
I am creating a test case to run Proteus using an external mesh of Tetgen format.
Mesh files contain: cylinder.node, cylinder.ele, cylinder.face. I used the following function call to load the mesh:
    mymesh=MeshTools.genMeshWithTetgen('cylinder')

this function reads only nodes and elements. 
My question is: how to load the .face file in order to define boundaries.

**Comment by cekees** [comment]
Did you figure this out? I `parun` has an option `-F` that reads the entire tetgen mesh from files, but it requires the full set of tegen mesh files: mesh.edge  mesh.ele  mesh.face  mesh.neigh  mesh.node
