### ISSUE TITLE
optimize the proteus build

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#688]
whoever does this well will be a hero. I think the way to do it right is create a compiler macro like PROTEUS_BUILD_ALL_SPACES and then go in RANS2P.h, etc. and use that macro to enable all the existing quadrature/fem space combinations while of PROTEUS_BUILD_ALL_SPACES is undefined only build 1 quadrature rule and FEM space pair per FEM Space (e.g. P1 with 3rd order gauss, P2 with 5th order gauss, etc.) @mquezada have done this sort of thing during development, but what I'm talking about would allow the default `make install` to be fast and `make install PROTEUS_BUILD_ALL_SPACES=1` to support a full range of options.

**Comment by adimako** [comment]
@manuel-quezada manuel has done something about it, suggest closing it @cekees

**Comment by cekees** [comment]
Yes, there are two resolutions

1) build with PROTEUS_OPT="-O0 -UNDEBUG" FC=gfortran CC=mpicc CXX=mpicxx make ..
2) Set the FULL_BUILD macro to 0
