### ISSUE TITLE
flcbdfWrappers.os mis-installed

### ISSUE THREAD

**Issue by jedbrown** [erdc/proteus#71]
With host-arch, it installs to `linux2/lib/python2.7/site-packages/$PETSC_ARCH/proteus/flcbdfWrappers.so`, thus needs to be copied to `linux2/lib/python2.7/site-packages/proteus/`

**Comment by adimako** [comment]
@cekees is still this an issue?

**Comment by cekees** [comment]
believe this was fixed with more recent "arch" hashdist profiles that @tridelat was using. reopen if needed.
