### ISSUE TITLE
chrono/ancf inconsistency

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#715]
test_mbd_chrono.py does not consistently pass. I suspect there is a memory issue either within chrono or within the chrono wrappers.

**Comment by adimako** [comment]
@cekees @tridelat  there seems to be some work done on this. Is it sorted?

**Comment by tridelat** [comment]
@adimako this is still an issue unfortunately

**Comment by tridelat** [comment]
@adimako @cekees this issue seems to now be solved with #845
