### ISSUE TITLE
Command-line PROTEUS_ARCH

### ISSUE THREAD

**Issue by jedbrown** [erdc/proteus#73]
It's currently cumbersome to switch PROTEUS_ARCH.  It should be a dead simple command-line parameter.

**Comment by adimako** [comment]
I think now it is pretty straightforward to change PROTEUS_ARCH. Usually the errors are not related to not being able to change architecture, but rather compilation errors with the stack. @cekees?

**Comment by cekees** [comment]
Thanks @adimako , agreed.
