### ISSUE TITLE
install failure in gdbm

### ISSUE THREAD

**Issue by ZhouleiJoeStone** [erdc/proteus#737]
when run make develop, I come across some error as below:

[INFO] Resolved package psutil to [u'/home/zhoulei/zhoulei/Project/Proteus/proteus/stack/pkgs/psutil.yaml']
[INFO] urllib failed to download (code: 502): http://ftp.heanet.ie/mirrors/gnu/gdbm/gdbm-1.11.tar.gz
[INFO] Retrying in 1 seconds, 2 tries remaining
[INFO] Press Control-C to give up
[INFO] urllib failed to download (code: 502): http://ftp.heanet.ie/mirrors/gnu/gdbm/gdbm-1.11.tar.gz
[INFO] Retrying in 2 seconds, 1 tries remaining
[INFO] Press Control-C to give up
[INFO] urllib failed to download (code: 502): http://ftp.heanet.ie/mirrors/gnu/gdbm/gdbm-1.11.tar.gz
[CRITICAL] You may wish to check your Internet connection or the remote server
Makefile:179: recipe for target '/home/zhoulei/zhoulei/Project/Proteus/proteus/linux2/artifact.json' failed
make: *** [/home/zhoulei/zhoulei/Project/Proteus/proteus/linux2/artifact.json] Error 127

It seems that the link address  http://ftp.heanet.ie/mirrors/gnu/gdbm/gdbm-1.11.tar.gz   for gdbm is invalid, because it fail again when I try to down gdbm-1.11 by wget or in the web bowser.

Is there any way to fix this issue?

**Comment by ZhouleiJoeStone** [comment]
OK, finally , I solve this link address problem of gdbm by modify the file stack/pkgs/gdbm.yaml.
$ cp /stack/pkgs/gdbm.yaml  /stack/pkgs/gdbm.yaml.bak
$ gedit gdbm.yaml
change the key & url to: 
- key: tar.gz:rwis6rhqlufrljff3fvhn6cs5ec5aun3
  url: http://ftp.gnu.org/gnu/gdbm/gdbm-1.11.tar.gz
And in my case, due to some write permissions, I have to run "make develop" in sudo.
That's all.

**Comment by cekees** [comment]
Glad you found a work around. Sometimes the mirrors aren't available and sometimes the source has actually moved.  You can also point to our source cache as well: https://github.com/erdc/proteus/wiki/Faster-and-more-stable-stack-builds-using-the-remote-caches#sources

Also, if you need to get new source you can do the following

./hashdist/bin/hit fetch http://ftp.gnu.org/gnu/gdbm/gdbm-1.11.tar.gz

That will give you the correct lines to paste into e.g. pkgs/gdbm.yaml.

**Comment by ZhouleiJoeStone** [comment]
https://github.com/erdc/proteus/wiki/Faster-and-more-stable-stack-builds-using-the-remote-caches#sources
Does it mean that the remote pre-built packages http://192.237.213.149/hashdist_ubuntu_14_04/bld  can also be used in ubuntu16.04 or ubuntu16.10?

**Comment by cekees** [comment]
We're waiting on provisioning of a new server instance to put more pre-built binaries up. Right now only 14.04 and debian_jessie are available. They might work for the newer versions of ubuntu, but I haven't tried it.

**Comment by dloney** [comment]
I've just had this issue as well. Maybe we need to change default where the makefile is pointing?

**Comment by cekees** [comment]
Did you add the source cache as described  here: https://github.com/erdc/proteus/wiki/Faster-and-more-stable-stack-builds-using-the-remote-caches#sources?

**Comment by adimako** [comment]
I will go ahead and close @cekees
