### ISSUE TITLE
Bug or memory leak / allocation error at RANS3PSed 

### ISSUE THREAD

**Issue by adimako** [erdc/proteus#742]
- CLF number is not updated properly - zeros values are added
- Receving nan output at residual array for RANS3PSed - though not always
- If print statement are inserted in RANS3PSed2D.h, then CFL values are not zero anymore (might indicate memory leak - allocation errors)
- To reproduce the error, use the gco_rans3p branch and this air water vv case https://github.com/erdc/air-water-vv/tree/gco_sed/2d/sediment/bed_sediment
- CFL number is updated in https://github.com/erdc/proteus/blob/gco_rans3p/proteus/mprans/RANS3PSed.h#L1075

**Comment by adimako** [comment]
I will keep working on it, but could you also give it a fresh look yourselves

**Comment by cekees** [comment]
@manuel-quezada are you able to reproduce this on the master branch?

**Comment by manuel-quezada** [comment]
No, after changing the definition of the cfl (to avoid having negative entries) my simulation goes all the way through.

**Comment by cekees** [comment]
Is that change in master now?

**Comment by manuel-quezada** [comment]
Not that I am aware. I think that @adimako incorporated that change in gco_rans3p.

**Comment by adimako** [comment]
Yes I did that change, but it did not solve the problem for me

**Comment by cekees** [comment]
I verified that you get nan residuals in rans3psed after sufficiently many steps have been taken. Looks to me like the vos or the sediment velocity is unstable.

**Comment by adimako** [comment]
Copy that, I did also play with the parameters a bit and it looks better. I am closing the issue.
