### ISSUE TITLE
is this a bug ?: shape.MeshOptions.constraints

### ISSUE THREAD

**Issue by xiaowang1999** [erdc/proteus#759]
Found in the following cases:
2d/numericalTanks/nonlinearWaves/MeshRefinement.py:        cons = shape.MeshOptions.constraints
2d/numericalTanks/randomWavesFast/MeshRefinement.py:        cons = shape.MeshOptions.constraints

**Comment by tridelat** [comment]
@xiaowang1999 what is the bug you are seeing with this?
This is an old way we used gmsh refinement options through python, more recent cases use a different `MeshRefinement.py` file.

**Comment by xiaowang1999** [comment]
I was trying to add a rectangle shape inside a tank, which activated this line. 
Error message: rectangle  object has no attribute MeshOptions. 
I was running Proteus version: 8498860fb7bb70eb627c14931eec690ec5024f16

**Comment by tridelat** [comment]
@xiaowang1999 you should be able to do: 
`my_rectangle.MeshOptions = mr.MeshOptions(my_rectangle)` to solve the problem (after importing `mr`).
Alternatively, you can remove all the mesh refinement options that use the `MeshRefinement` module, especially is you do not use gmsh (`use_gmsh=False`).
Again, this is an old way to interface with gmsh so it should be updated in the future.

**Comment by cekees** [comment]
@xiaowang1999 reopen this if you are still working on it.
