### ISSUE TITLE
Mass Correction: MCorr.postStep() behavior

### ISSUE THREAD

**Issue by zhang-alvin** [erdc/proteus#766]
I'm having some trouble understanding the mass correction procedure in terms of how the degrees of freedom are manipulated. In MCorr.postStep(), there are the following lines:
(https://github.com/erdc/proteus/blob/master/proteus/mprans/MCorr.py#L169-L173)
```
            self.lsModel.u[0].dof += self.massCorrModel.u[0].dof
            self.lsModel.q[('u', 0)] += self.massCorrModel.q[('u', 0)]
            self.lsModel.ebqe[('u', 0)] += self.massCorrModel.ebqe[('u', 0)]
            self.lsModel.q[('grad(u)', 0)] += self.massCorrModel.q[('grad(u)', 0)]
            self.lsModel.ebqe[('grad(u)', 0)] += self.massCorrModel.ebqe[('grad(u)', 0)]
```
This modifies the degrees of freedom and quadrature point fields of the level-set model, but this modification isn't reflected in the modelList.uList set of unknowns. So the result is the following sequence:

1.  MCorr.postStep() updates quadrature point fields and u.dof[:] of the level-set model
2.  RANS2P uses modified quadrature point fields
3.  Solver reaches level-set model again. When computing the residual, the modelList.uList set of unknowns writes over the u.dof[:] array.

This means that RANS2P uses the mass-corrected level-set field, but the level-set model is updating the uncorrected level-set field from the previous time step. 

Is this expected behavior or am I interpreting something wrong?

Example of behavior at step 3 in NCLS.getResidual(), just before calling `self.setUnknowns()` at https://github.com/erdc/proteus/blob/master/proteus/mprans/NCLS.py#L1185:

```
(Pdb) print self.u[0].dof.mean()
0.0754403492887
(Pdb) print u.mean()
0.0754478228232
```
 and just after the call

```
(Pdb) print self.u[0].dof.mean()
0.0754478228232
(Pdb) print u.mean()
0.0754478228232
```

**Comment by zhang-alvin** [comment]
There's also a difference between VOF.uList[:] and VOF.levelModelList[0].u.dof[:] as well because of the call to setMassQuadrature() in postStep():
https://github.com/zhang-alvin/proteus/blob/master/proteus/mprans/MCorr.py#L1140.

**Comment by wacyyang** [comment]
@zhang-alvin Here are several remarks on your concern
1.  Yes. `.uList` is different from `.u.dof`.  They have different structure and `xxx.u.dof` has the additional information of Dirichlet boundary condition.
2.  The 3 execution sequence you said is correct for me. But, it does not mean that the uncorrected value is used in the next step because the reference is used https://github.com/erdc/proteus/blob/05d9d7bf0912f7e1831ca04f149a803ab605e2d6/proteus/mprans/NCLS.py#L703
3. In each time step, several Newton iteration steps are needed. So that is why in `xxx.setUnknowns` of `xxx.getResidual` the variable `xxx.u.dof` is assigend to be `u` before computing the residual (of `u`).

**Comment by wacyyang** [comment]
@zhang-alvin In you example, can you print out the location of the different values in `phi` and `phi_correct`? I think the difference is on the Dirichlet boundary. For your question, I think they are the same (except Dirichlet boundary information) when Newton Solver finishes. But, they may become different after `postStep`.

**Comment by zhang-alvin** [comment]
@wacyyang If I compare the two structures: `print u==self.u[0].dof` in `getResidual()` before `setUnknowns`, I have that all values are `False` which is to say that no values are the same between `phi` and `phi_correct`. 

I don't see why we want them to become different after `postStep`.

**Comment by zhang-alvin** [comment]
After a discussion with @wacyyang, most of my confusion is resolved. The heart of the issue is the choice in initial guess for the level-set model. It shouldn't be a problem that uList or `phi` is used as an initial guess instead of `phi_corrected` because the initial guess can be "anything". 

My next question is why is `phi_corrected` not used instead as the initial guess?

**Comment by cekees** [comment]
@zhang-alvin and @wacyyang thanks for looking at this. The uList storage is manipulated following NumericalSolution.pre/postStep after the models' pre/postStep based on what is provided in the copyInstructions: https://github.com/erdc/proteus/blob/master/proteus/NumericalSolution.py#L1648. I'll let you work through the logic on your own, but the basic idea is to provide some instructions to either a) set the uList values to zero b) copy the uList values from some other model, or c) reset the uList from the models own internal DOF.  

It's true that the uList storage is essentially the initial guess to the nonlinear iteration so the results should be independent of it for tight tolerances (and convergent nonlinear iterations). Specifically for  NCLS and VOF, which are linear models anyway, it's unlikely to have an effect and would trigger an extra residual call.  Likewise MCORR should be reset to zero anyway. RDLS could be sensitive to the initial guess though. You're welcome to play around with the copyInstructions on your branch to see if you get better results.

**Comment by zhang-alvin** [comment]
@cekees Thanks for the explanation. Resetting the uList models will make information transfer simpler when using MeshAdapt and the code much cleaner.

`postStep()` also operates on the boundary quadrature for the gradient of the level-set:

```self.lsModel.ebqe[('grad(u)', 0)] += self.massCorrModel.ebqe[('grad(u)', 0)]```
in https://github.com/erdc/proteus/blob/master/proteus/mprans/MCorr.py#L173

but I don't see where the `ebqe[('grad(u)',0)]` vector is populated on each time step or reset. Instead, I'm seeing that the `MCorr.postStep()` is the only time `ebqe[('grad(u)',0]` is modified, which leads to a continuous history of the values from the beginning of the simulation, which doesn't seem right. And this data structure is used somewhere because modifying this behavior changes the pressure gauge results for my test case. Where is this structure used and is this the expected behavior?

`self.massCorrModel.ebqe[('grad(u)',0)]` structure is populated by 
```ebqe_n[ebNE_kb_nSpace+I] = grad_u_ext[I]/norm;``` 
in `https://github.com/erdc/proteus/blob/master/proteus/mprans/MCorr.h#L890

**Comment by cekees** [comment]
The self.lsModel.ebqe[('grad(u)', 0)]  for a signed distance field is also the unit normal of the level set (n_ls), which is used in various places in the level set methodology and set/calculated in in NCLS and RDLS.  When we correct the level set we also correct the gradient as we're doing here, which is consistent with the definition of the level set correction. That is, self.massCorrModel.ebqe[('grad(u)',0)] is the correction to the gradient of the level set. The renormalizing of the gradient correction is questionable, but I don't think it relates to your problems with MeshAdapt.

As I said, you can play around with the copyInstructions on your branch, but I don't think you need to be modifying this code to fix your issues with meshAdapt. If you need to reset information at the various quadrature point sets after adaptivity, then do it by calling the proper functions, as is done in postStep and preStep in NumericalSolution and/or by evaluation residuals after adaptivity.
