### ISSUE TITLE
clean up macro usage in EV implementations

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#819]
We're using macros in C++ header files in a lot of places (SW2DCF.h, VOF.h,... ) where we should be using inline functions. Since those files get included in other files (e.g. the cython files), they can and do get expanded in unintended locations. This bit me on some recent compiles, so I added one fix here that can be used as an example: https://github.com/erdc/proteus/pull/810/files#diff-3f17cf93e98ac1999a572f29010247e9L29
That's not to say they all have to be replaced, but I think as  rule it's better to use inline functions for reasonably complicated functions as well as use unique, capitalized names for macros. It would also be good to document the functions and macros.

**Comment by manuel-quezada** [comment]
I don't have automated tests for the SWEs so I don't want to make that change yet. I will change all the other files and make sure I didn't break any test. After that I will think about how to handle safely the SW2DCV.h file.

**Comment by adimako** [comment]
@cekees @manuel-quezada does #822 solve this one

**Comment by cekees** [comment]
Yes!
