### ISSUE TITLE
Convert lapackWrappersModule.c and superluWrappersModule.c to clapackWrappers.pyx and csuperluWrappersModule.pyx

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#848]
- [ ] create clapackTest.pyx module and add forward declarations for functions in proteus_lapack.h  (see https://github.com/erdc/proteus/blob/master/proteus/canalyticalSolutions.pyx#L3)
- [ ] add clapackTest extension build to setup.py (see line for canalyticalSolutions)
- [ ] add test_lapack.py to proteus/tests (see test_analyticalSolutions.py)
- [ ] add python wrapper functions  (see https://github.com/erdc/proteus/blob/master/proteus/canalyticalSolutions.pyx#L49)
- [ ] ensure wrappers replace everything exposed in lapackWrappersModule.c and pass tests
- [ ] rename clapackTest.pyx to clapack.pyx and remove lapackWrappersModule.c and related setup.py lines

See http://docs.cython.org/en/latest/src/tutorial/external.html

**Comment by alistairbntl** [comment]
@cekees - Quick question.  The functions declared in `proteus_lapack.h` have the pure LAPACK handles (e.g. `dgetrf_` etc).  In contrast, the function wrappers declared in `lapackWrappersModule.c` (no corresponding `.h` file btw, so I'm guessing these functions are not forward declared anywhere) have names like `denseFactorPrepare` / `lapackWrappersDenseFactorPrepare`.  Am I correct to assume that my `clapack.pyx` file should actually be forward declaring these functions, not the LAPACK handles?

**Comment by cekees** [comment]
You want to declare what you will use from proteus_lapack.h and proteus_blas.h and then you want to define the classes and functions that are defined in lapackWrappersModule.c.  This a little more advanced than just wrapping functions because lapackWrappersModule actually defines a new  Python class (type) called DenseFactor and some functions that operate on that new type (lapackWrappersDenseFactorPrepare, etc.).  See http://docs.cython.org/en/latest/src/tutorial/cdef_classes.html

**Comment by cekees** [comment]
Another way to look  at is how the lapackWrappers modules is  used:

Creating a DenseFactor object:
```
self.denseFactor = lapackWrappers.DenseFactor(self.n)
```
Preparing  (factoring) the object:
```
lapackWrappers.denseFactorPrepare(self.n,
                                              self.L,
                                              self.denseFactor)
```
Solving a system with the prepared (factored) object:
```
lapackWrappers.denseFactorSolve(self.n,
                                            self.L,
                                            self.denseFactor,
                                            u)
```

Calculating the eigenvalue with the object:

```
            lapackWrappers.denseCalculateEigenvalues(self.JOBVL,
                                                     self.JOBVR,
                                                     self.n,
                                                     self.Leig,
                                                     self.n,
                                                     self.eigenvalues_r,
                                                     self.eigenvalues_i,
                                                     self.leftEigenvectors,
                                                     self.n,
                                                     self.rightEigenvectors,
                                                     self.n,
                                                     self.work,
                                                     5*self.n)```
