### ISSUE TITLE
remove triangleWrappersModule.c

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#850]
I propose that  we remove this entirely instead of developing new Cython wrappers. Instead, replace it with tools that simply call the triangle executable, as we do with tetgen in 3D.  I believe we only need to reproduce the behavior of the `TriangleBaseMesh` constructor from TriangleTools, unless I'm missing other uses of TriangleTools or TriangleUtils in other proteus modules.

```MeshTools.py:    from proteus import TriangleTools
MeshTools.py:        tmesh = TriangleTools.TriangleBaseMesh(baseFlags="Yp",
MeshTools.py:        from . import TriangleTools
MeshTools.py:        tmesh = TriangleTools.TriangleBaseMesh(baseFlags=self.triangleOptions,
NumericalSolution.py:from . import TriangleTools
NumericalSolution.py:                        tmesh = TriangleTools.TriangleBaseMesh(baseFlags=n.triangleOptions,
```

**Comment by tridelat** [comment]
Closing as #882 was merged
