### ISSUE TITLE
Profiling.logEvent accumulating memory space

### ISSUE THREAD

**Issue by tridelat** [erdc/proteus#901]
Calls to Profiling.logEvent accumulate over time and fill up memory if it is not dumped into external file, which can slow down or freeze simulations (or the machine running it).
This can happen when running a test case in python without solving a proteus model for example while still using code that has logEvent calls (e.g. in proteus.mbd)

**Comment by adimako** [comment]
Tristan, you have to set Profiling.flushBuffer=True I think. When we run proteus, this is switched on by the default_s module, but when you do tests, this has to be switched on manually. I do not know if it is worth keeping it False as default.
https://github.com/erdc/proteus/blob/master/proteus/Profiling.py#L38

**Comment by tridelat** [comment]
@adimako @cekees  `Profiling.flushBuffer = True` does not solve the issue, but setting `Profiling.procID` to something else than `None` solves it. The only thing is that there is still nothing printed on stdout then, but it can be solved by setting the other options like `logLevel`, `verbose`, and `logFile`, so I think that is okay as a workaround.
