### ISSUE TITLE
Potential bug in TwoPhase flow & relaxation zones?

### ISSUE THREAD

**Issue by adimako** [erdc/proteus#966]
We have tried running the following case and it seems like there is something off with the relaxation zone. 

https://github.com/erdc/air-water-vv/tree/overtopping/2d/waveOvertopping/Random_waves_CLASH 

We have been working with it for some time now. We noticed that moving the assembleDomain command lower than the setGeneration and setAbsorption kills the waves inside the generaiton zone. 

Having the assembleDomain in the place where is it now, allows for some wave propagation but this is not in any way enough to create overtopping events.

Removing completely the generation zone, initially creates the correct amount of overtopping, but after a while then the wave field gets contaminated by reflections.

I recommend reviewing the case file first to see if we do anything wrong

Aggelos

**Comment by tridelat** [comment]
@adimako if you do `assembleDomain(...)` before defining the generation zones, you should have the same results as if you removed the generation zones definition, as it means that the auxiliary variables will not be added to the `domain` instance at all.
I had a quick look at the file and the relaxation zones definition seem fine (apart from having assembleDomain call before it).
Were the cases with and without generation zones run with the exact same script? Again, I would expect the same results when commenting out the generation/absorption zones as the case where they are not defined

**Comment by adimako** [comment]
Understood. 
But when we put the definition after the setGeneration zone etc., it will kill the waves. 

@msklia do you have a snapshot from an old run showing that the wave does not propagate? Or could you send a video?

**Comment by tridelat** [comment]
@adimako could you try the wave propagation with `Tank2D` class instead of `Tank2DWithObstable` as well? The gen/abs definitions are overridden in `Tank2DWithObstacle` (subclass of `Tank2D`)

**Comment by adimako** [comment]
We will try, but with the old scripts (with p and n files) seems to run ok with Tank2DWithObstacle

**Comment by tridelat** [comment]
I think this line should be added (after assembling the domain):
```
myTpFlowProblem.Parameters.Models.rans2p.auxiliaryVariables += domain.auxiliaryVariables['twp']
```
Ideally, this should be done automatically in the future, but for now this line must be added in the main file.
My concern is that if you didn't add this line, I don't think the relaxation zones should even be linked at all, so I don't know why it killed the wave generation.

**Comment by adimako** [comment]
So move <assembleDomain> at the end and add this line

**Comment by tridelat** [comment]
Yes, `assembleDomain` after everything is done with the geometry and auxiliaryVariables

**Comment by tridelat** [comment]
@adimako is this solved?

**Comment by adimako** [comment]
We are still not getting the correct wave. 
![image](https://user-images.githubusercontent.com/8258298/59677627-362b4880-91c2-11e9-9bbd-cfab3eacf12c.png)
In the figure above, we have old script, new script and theoretical at the exit of the relaxation zone.  You can see that the new script is doing something random. 

We get the same issues at the boundary, we are investigating to see if we have set something wrong

**Comment by adimako** [comment]
We have forgot to put Unsteady flow boundary conditions in both scripts, re-running now

**Comment by adimako** [comment]
Differences:
-At Mcorr model, checkMass is False for the TWP app

**Comment by msklia** [comment]
Hi all, after some searching in both the old script and the two phase flow app, I have written down some of the differences that exist in the values of the numerical parameters. Please find it attached in the following spreadsheet. In the file you can also find comments on the parameters used and the ones that were recently changed locally to check their influence on the overtopping discharge results. 

[TwophaseFlow_parameters.xlsx](https://github.com/erdc/proteus/files/3500467/TwophaseFlow_parameters.xlsx)

**Comment by adimako** [comment]
All, I think we are all happy that the two phase flow App is working. I will close issue as not being relevant anymore
